modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[dependencies.angry_villagers]]
    modId="forge"
    mandatory=true
    versionRange="[47.3.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.angry_villagers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.angry_villagers]]
    modId="village_flag"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Villagers with very low reputation toward a player become illagers, who claim the player's flag as their workstation, neutralizing it.
'''
